apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::627818603677:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-XZh6UswCHLgl
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::627818603677:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-30T17:48:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1311"
  uid: 0418b514-57bb-4a81-8957-5ea489e5d8f6
